### PR TITLE
success

### PR DESCRIPTION
**Pull request by looSeeCan2**
So, I did a successfull merge and pull, but, I forgot to save the note file. just doing one last commit for practice.

### CODE REVIEW

**Comment by looSeeCan2** [comment]
Do I have to comment first

**Comment by looSeeCan2** [comment]
I think the main branch has to review first maybe

**Comment by looSeeCan** [comment]
so the home laptop commits. I checked for the message and found the pull request >  Review reqiured > Add your review

**Review by looSeeCan — APPROVED** [review]

**Comment by looSeeCan** [comment]
after I we click the add review > review green button on right hand corner > accept review

**Comment by looSeeCan** [comment]
click green merge request button

**Comment by looSeeCan** [comment]
delet branch. Idk what happends if you dont delete branch.

**Comment by looSeeCan** [comment]
so I went back to my machine > vscode > gitbash terminal> git pull: I got this message: 

Your configuration specifies to merge with the ref 'refs/heads/home-laptop'
from the remote, but no such ref was fetched.

**Comment by looSeeCan** [comment]
fixed this issue by going  back on gitHub desktop and switching back to master. then pulling the changes

**Pull request merged**
